# Generated by Django 4.2.4 on 2023-08-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='img1.jpg', null=True, upload_to='image/%Y', verbose_name='Изображение'),
        ),
    ]
