# Generated by Django 4.2.4 on 2023-08-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_post_text_alter_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image/%Y', verbose_name='Изображение'),
        ),
    ]
